version: '2'

networks:
  kafka-test:
    driver: bridge

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - kafka-test
    depends_on:
      - zookeeper
      - kafka

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=dpsxpftm!!
      - ZOO_HEAP_SIZE=128
    networks:
      - kafka-test

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "19092:9092"
    environment:
      - KAFKA_HEAP_OPTS=-Xms128M -Xmx256M
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=dpsxpftm!!
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    networks:
      - kafka-test

  kafka-connector:
    image: quay.io/strimzi/kafka:0.21.1-kafka-2.7.0
    command: [
      "sh", "-c",
      "bin/connect-standalone.sh config/connect-standalone.properties config/CamelAzurestorageblobSinkConnector.properties"
    ]
    volumes:
      - ./connectors:/opt/kafka/connectors
      - ./config:/opt/kafka/config
    networks:
      - kafka-test
    depends_on:
      - zookeeper
      - kafka
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_HEAP_OPTS: "-Xms32M -Xmx128M"
  
  telegraf:
    image: 'telegraf:latest'
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - kafka-test
    depends_on:
      - kafdrop
